### PR TITLE
El comments

### PR DESCRIPTION
**Pull request by ErikLindstrom42**
# Description
When the user selects a post, they can now select a "Comments" button that shows them all the comments on that post. They can now add, edit, and delete comments.

Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
# Testing Instructions
Checkout this branch.  Ensure that all previously working features are still functional.  Verify that you can add a comment on a post as well as edit and delete comments.
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by PMurphy1940 — CHANGES_REQUESTED** [review]
All the functionality is there and working properly, but I am able to edit and delete other users comments. That probably shouldn't happen

**Comment by ErikLindstrom42** [comment]
> All the functionality is there and working properly, but I am able to edit and delete other users comments. That probably shouldn't happen

Buttons and edit/delete functionality now blocked to all users except the one that created the comment. Please recheck

**Review by MandasK — APPROVED** [review]
Works as directed!

**Review by PMurphy1940 — APPROVED** [review]
Working well. Can't directly navigate to another users comment and modify. Good job!

**Pull request merged**
